Repository The-HaiKaw-Pr0tocol/MemoraDB, pull requests merged in 2025-07, with the labels that each got.

#1 feat: implement simple TCP server that responds with PONG to clients
  src/main.c
Labels: enhancement

#2 - feat(multi-threading): Implemented multi-threading support for multiple clients, supporting PING and EXIT client commands.
  .gitignore
  src/client.c
  src/main.c
Labels: documentation, enhancement

#5 feat : implement first version of Redis protocol parser
  .gitignore
  src/client.c
  src/main.c
Labels: enhancement

#8 - Refactored the MemoraDB server and client utilities using C-code best practices / conventions.
  src/server/main.c
  src/server/main.h
  src/utils/client.c
  src/utils/client.h
Labels: refactoring

#10 feat: Refactored code using helper function for a more consistent logging formatting
  src/server/server.c
  src/server/server.h
  src/utils/client.c
  src/utils/client.h
  src/utils/log.c
  src/utils/log.h
Labels: enhancement, refactoring

#11 Add script for automation
  build.sh
  src/server/server.c
Labels: automation

#12 - feat(hashTable Storage): Added hash table storage for efficient data persistence (SET), and retreivel (GET).
  .gitignore
  build.sh
  src/server/server.c
  src/server/server.h
  src/utils/hashTable.c
  src/utils/hashTable.h
Labels: feature

#14 chore(build): Add Makefile and refactor build.sh to use it
  Makefile
  build.sh
  src/client/client.c
  src/parser/parser.c
  src/parser/parser.h
  src/server/server.c
  src/server/server.h
  src/utils/logo.c
  src/utils/logo.h
Labels: automation

#17 - doc: Added the README.md file.
  README.md
Labels: documentation

#16 - feat(parser/makefile): Added RPUSH command support and refactor hash table for value types + Removed Hardcoded makefile paths.
  Makefile
  src/parser/parser.c
  src/parser/parser.h
  src/utils/hashTable.c
  src/utils/hashTable.h
  src/utils/list.c
  src/utils/list.h
Labels: feature, automation

#18 - fix(parser): Updated response formatting for commands to return raw RESP format
  src/parser/parser.c
Labels: feature

#25 Add LPUSH and LRANGE List Operations
  .gitignore
  src/parser/parser.c
  src/parser/parser.h
  src/utils/hashTable.c
  src/utils/hashTable.h
  src/utils/list.c
  src/utils/list.h
Labels: feature

#27 - feat(lists): Completed full LLEN CLI support for the RESP parser
  src/parser/parser.c
  src/utils/hashTable.c
  src/utils/hashTable.h
Labels: feature, lists
